services:
  php:
    build:
      context: 'php-apache/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php-apache
    restart: always
    environment:
      SERVER_NAME: localhost
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
    depends_on:
      - mysql
    networks:
      - localhost
  mysql:
    image: ${MYSQL_VERSION}
    container_name: mysql
    restart: always
    command: --pid-file /var/lib/mysql/mysqld.pid --lower_case_table_names=1
    environment:
      MYSQL_ROOT_HOST: '%'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ${PROJECT_PWD}/mysql_data:/var/lib/mysql
    networks:
      - localhost
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - localhost
networks:
  localhost:
